# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rails-localization 1.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rails-localization"
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["E-Max"]
  s.date = "2014-01-31"
  s.description = "This gem allows you to localize your rails application with ease"
  s.email = "max@studentify.nl"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".ruby-gemset",
    ".ruby-version",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/rails-localization.rb",
    "lib/rails-localization/controller.rb",
    "lib/rails-localization/engine.rb",
    "lib/rails-localization/i18n.rb",
    "lib/rails-localization/route_set.rb",
    "lib/rails-localization/router.rb",
    "lib/rails-localization/url_options.rb",
    "lib/rails_localization.rb",
    "rails-localization.gemspec"
  ]
  s.homepage = "http://github.com/kot-begemot/rails-localization"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.1"
  s.summary = "Rails localization Gem"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 5.0.0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.0"])
    else
      s.add_dependency(%q<rails>, [">= 5.0.0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 5.0.0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.0"])
  end
end
